import { Area } from "@/types";
import {
  Syringe,
  Heart,
  Slice,
  Scissors,
  Baby,
  Sparkles,
  Flower2,
  Fingerprint,
  FlaskConical,
  Activity,
  Dna,
  Sandwich,
  Droplet,
  Worm,
  Users,
  Briefcase,
  Dumbbell,
  Brain,
  Apple,
  Eye,
  Bone,
  Stethoscope,
  Ear,
  Microscope,
  Wind,
  RadioTower,
  Thermometer,
  Shell,
} from "lucide-react";

export const areasData: Area[] = [
  { name: "Anestesiologia", icon: Syringe, image: "anestesiologia.png" },
  { name: "Cardiologia", icon: Heart, image: "cardiologia.png" },
  { name: "Cirurgia Cardiovascular", icon: Heart, image: "cirurgia-cardiovascular.png" },
  { name: "Cirurgia Geral", icon: Slice, image: "cirurgia-geral.png" },
  { name: "Cirurgia Pediátrica", icon: Scissors, image: "cirurgia-pediatrica.png" },
  { name: "Cirurgia Plástica", icon: Sparkles, image: "cirurgia-plastica.png" },
  { name: "Cuidados Paliativos", icon: Flower2, image: "cuidados-paliativos.png" },
  { name: "Dermatologia", icon: Fingerprint, image: "dermatologia.png" },
  { name: "Endocrinologia", icon: FlaskConical, image: "endocrinologia.png" },
  { name: "Fisioterapia", icon: Activity, image: "fisioterapia.png" },
  { name: "Genética Médica", icon: Dna, image: "genetica-medica.png" },
  { name: "Gastroenterologia", icon: Sandwich, image: "gastroenterologia.png" },
  { name: "Ginecologia", icon: Baby, image: "ginecologia.png" },
  { name: "Hematologia", icon: Droplet, image: "hematologia.png" },
  { name: "Infectologia", icon: Worm, image: "infectologia.png" },
  { name: "Medicina de Família", icon: Users, image: "medicina-familia.png" },
  { name: "Medicina do Trabalho", icon: Briefcase, image: "medicina-trabalho.png" },
  { name: "Medicina Esportiva", icon: Dumbbell, image: "medicina-esportiva.png" },
  { name: "Neurologia", icon: Brain, image: "neurologia.png" },
  { name: "Nutrição", icon: Apple, image: "nutricao.png" },
  { name: "Oftalmologia", icon: Eye, image: "oftalmologia.png" },
  { name: "Ortopedia", icon: Bone, image: "ortopedia.png" },
  { name: "Oncologia", icon: Stethoscope, image: "oncologia.png" },
  { name: "Otorinolaringologia", icon: Ear, image: "otorinolaringologia.png" },
  { name: "Patologia", icon: Microscope, image: "patologia.png" },
  { name: "Pediatria", icon: Baby, image: "pediatria.png" },
  { name: "Pneumologia", icon: Wind, image: "pneumologia.png" },
  { name: "Psiquiatria", icon: Brain, image: "psiquiatria.png" },
  { name: "Radiologia", icon: RadioTower, image: "radiologia.png" },
  { name: "Reumatologia", icon: Thermometer, image: "reumatologia.png" },
  { name: "Urologia", icon: Shell, image: "urologia.png" },
];
