export const GenderOptions = [
  { label: "Homem", value: "male" },
  { label: "Mulher", value: "female" },
  { label: "Outro", value: "other" },
];
export const IdentificationTypes = [
  "Birth Certificate",
  "Driver's License",
  "Medical Insurance Card/Policy",
  "Military ID Card",
  "National Identity Card",
  "Passport",
  "Resident Alien Card (Green Card)",
  "Social Security Card",
  "State ID Card",
  "Student ID Card",
  "Voter ID Card",
];

export const StatusIcon = {
  scheduled: "/assets/icons/check.svg",
  pending: "/assets/icons/pending.svg",
  canceled: "/assets/icons/cancelled.svg",
  finalized: "/assets/icons/finalized.svg",
};

export const specialties = [
  "Cardiologia",
  "Dermatologia",
  "Ginecologia",
  "Pediatria",
  "Ortopedia",
  "Oftalmologia",
  "Neurologia",
  "Psiquiatria",
  "Endocrinologia",
  "Gastroenterologia",
  "Oncologia",
  "Urologia",
  "Reumatologia",
  "Pneumologia",
  "Otorinolaringologia",
  "Fisioterapia",
  "Nutrição",
  "Anestesiologia",
  "Medicina de Família",
  "Medicina do Trabalho",
  "Medicina Esportiva",
  "Radiologia",
  "Patologia",
  "Cirurgia Geral",
  "Cirurgia Plástica",
  "Cirurgia Pediátrica",
  "Cirurgia Cardiovascular",
  "Hematologia",
  "Infectologia",
  "Genética Médica",
  "Cuidados Paliativos",
];
