export const GenderOptions = [
  { label: "Homem", value: "male" },
  { label: "Mulher", value: "female" },
  { label: "Outro", value: "other" },
];
export const IdentificationTypes = [
  "Certidão de Nascimento",
  "Carteira de Motorista",
  "Cartão/Apólice de Seguro Médico",
  "Carteira de Identidade Militar",
  "Carteira de Identidade Nacional",
  "Passaporte",
  "Cartão de Residente Estrangeiro (Green Card)",
  "Cartão de Seguridade Social",
  "Carteira de Identidade Estadual",
  "Carteira de Estudante",
  "Carteira de Eleitor",
];

export const StatusIcon = {
  scheduled: "/assets/icons/check.svg",
  pending: "/assets/icons/pending.svg",
  canceled: "/assets/icons/cancelled.svg",
  finalized: "/assets/icons/finalized.svg",
};

export const specialties = [
  "Cardiologia",
  "Dermatologia",
  "Ginecologia",
  "Pediatria",
  "Ortopedia",
  "Oftalmologia",
  "Neurologia",
  "Psiquiatria",
  "Endocrinologia",
  "Gastroenterologia",
  "Oncologia",
  "Urologia",
  "Reumatologia",
  "Pneumologia",
  "Otorinolaringologia",
  "Fisioterapia",
  "Nutrição",
  "Anestesiologia",
  "Medicina de Família",
  "Medicina do Trabalho",
  "Medicina Esportiva",
  "Radiologia",
  "Patologia",
  "Cirurgia Geral",
  "Cirurgia Plástica",
  "Cirurgia Pediátrica",
  "Cirurgia Cardiovascular",
  "Hematologia",
  "Infectologia",
  "Genética Médica",
  "Cuidados Paliativos",
];
